FROM arm64v8/alpine:latest

# For cross building on amd64 host
COPY qemu-aarch64-static /usr/bin

RUN apk add --update monit bash curl
COPY docker-entrypoint.sh /

VOLUME /etc/monit
EXPOSE 2812
ENTRYPOINT ["bash", "/docker-entrypoint.sh"]
CMD ["monit", "-c", "/etc/monit/monitrc", "-I"]
