FROM arm32v7/alpine:latest

# For cross building on amd64 host
COPY qemu-arm-static /usr/bin

RUN apk add --update monit bash curl \
  && mkdir -p /var/lib/monit /etc/monit/monit.d
COPY docker-entrypoint.sh /

VOLUME /etc/monit
EXPOSE 2812
ENTRYPOINT ["bash", "/docker-entrypoint.sh"]
CMD ["monit", "-c", "/etc/monit/monitrc", "-I"]
