FROM arm64v8/alpine:latest

# For cross building on amd64 host
COPY qemu-aarch64-static /usr/bin

RUN apk add --update monit bash curl
RUN mkdir -p /var/lib/monit

EXPOSE 2812
ENTRYPOINT ["monit", "-c", "/etc/monit/monitrc", "-I"]
